# Generated by Django 4.2.5 on 2023-10-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
